[tool.poetry]
name = "api"
version = "0.1.0"
description = ""
authors = ["Bart van Arnhem <bart@orbisk.com>"]

[tool.poetry.dependencies]
python = "^3.9"
flask = "^3.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
